name: Run Integration Script

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'The URL of the repository to clone'
        required: true
        type: string
      builder:
        description: 'The builder argument for the integration script'
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repo_url }}
        token: ${{ secrets.PAT }}
        fetch-depth: 0  # Fetch the entire history for all branches and tags

    - name: Run integration script
      run: ./scripts/integration.sh --builder ${{ github.event.inputs.builder }}
      working-directory: ${{ github.workspace }}  # Set working directory to the cloned repository
